#!/usr/bin/env python3
"""Generate the extension's new tab page from the root index.html.

Manifest V3 refuses to run inline scripts, and index.html keeps all of its
JavaScript inline so that the page works as a standalone file. Rather than
maintain two copies of it, this lifts the inline script out into newtab.js and
writes a newtab.html that loads it.

    cd extension && python3 build-newtab.py

Run it after editing index.html. Both generated files are committed, so the
extension loads unpacked without anyone needing to run a build first.
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "index.html"
HTML_OUT = HERE / "newtab.html"
JS_OUT = HERE / "newtab.js"

BANNER = "Generated by build-newtab.py from ../index.html — edit that file, not this one."

# Inline <script> blocks only: anything with a src= is already external.
INLINE_SCRIPT = re.compile(r"<script(?![^>]*\bsrc=)[^>]*>(.*?)</script>", re.DOTALL | re.IGNORECASE)


def main() -> int:
    if not SOURCE.exists():
        print(f"error: {SOURCE} not found", file=sys.stderr)
        return 1

    html = SOURCE.read_text(encoding="utf-8")
    blocks = INLINE_SCRIPT.findall(html)

    if not blocks:
        print("error: no inline <script> found in index.html", file=sys.stderr)
        return 1

    script = "\n\n".join(block.strip() for block in blocks)
    if "</script" in script.lower():
        print("error: inline script contains a closing script tag", file=sys.stderr)
        return 1

    # The first inline block becomes the external reference; the rest are folded
    # into the same file and dropped from the markup.
    seen = 0

    def replace(_match: "re.Match[str]") -> str:
        nonlocal seen
        seen += 1
        return '<script src="newtab.js"></script>' if seen == 1 else ""

    page = INLINE_SCRIPT.sub(replace, html)
    page = page.replace("<head>", f"<head>\n<!-- {BANNER} -->", 1)

    HTML_OUT.write_text(page, encoding="utf-8")
    JS_OUT.write_text(f"// {BANNER}\n\n{script}\n", encoding="utf-8")

    print(f"newtab.html  {len(page):>7,} bytes")
    print(f"newtab.js    {len(script):>7,} bytes  ({len(blocks)} inline block(s) lifted)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
