// Generated by build-newtab.py from ../index.html — edit that file, not this one.

(function () {
  var STORAGE_SHORTCUTS = 'homepage.shortcuts';
  var STORAGE_THEME = 'homepage.theme';
  var STORAGE_ENGINE = 'homepage.engine';
  var STORAGE_COLORS = 'homepage.themeColors';
  var STORAGE_GROUPS = 'homepage.groups';
  var STORAGE_ACTIVE_GROUP = 'homepage.activeGroup';

  var defaultShortcuts = [
    { name: 'GitHub', url: 'https://github.com' },
    { name: 'YouTube', url: 'https://youtube.com' },
    { name: 'Gmail', url: 'https://mail.google.com' },
    { name: 'Reddit', url: 'https://reddit.com' }
  ];

  var editing = false;
  var editingIndex = null;
  var dragIndex = null;

  var grid = document.getElementById('shortcutsGrid');
  var groupTabsEl = document.getElementById('groupTabs');
  var editBtn = document.getElementById('editBtn');
  var settingsBtn = document.getElementById('settingsBtn');
  var settingsPanel = document.getElementById('settingsPanel');
  var panelClose = document.getElementById('panelClose');
  var themeGrid = document.getElementById('themeGrid');
  var modalOverlay = document.getElementById('modalOverlay');
  var modalTitle = document.getElementById('modalTitle');
  var tileNameInput = document.getElementById('tileName');
  var tileUrlInput = document.getElementById('tileUrl');
  var tileGroupSelect = document.getElementById('tileGroup');
  var modalSave = document.getElementById('modalSave');
  var modalCancel = document.getElementById('modalCancel');
  var modalDelete = document.getElementById('modalDelete');
  var searchForm = document.getElementById('searchForm');
  var searchInput = document.getElementById('searchInput');
  var searchClear = document.getElementById('searchClear');
  var engineSelect = document.getElementById('engineSelect');

  function loadShortcuts() {
    try {
      var raw = localStorage.getItem(STORAGE_SHORTCUTS);
      if (raw) return JSON.parse(raw);
    } catch (e) {}
    return defaultShortcuts.slice();
  }

  function saveShortcuts(list) {
    localStorage.setItem(STORAGE_SHORTCUTS, JSON.stringify(list));
  }

  function loadGroups() {
    try {
      var raw = JSON.parse(localStorage.getItem(STORAGE_GROUPS));
      if (Array.isArray(raw)) return raw;
    } catch (e) {}
    return [];
  }

  function saveGroups(list) {
    localStorage.setItem(STORAGE_GROUPS, JSON.stringify(list));
  }

  var groups = loadGroups();
  var activeGroup = localStorage.getItem(STORAGE_ACTIVE_GROUP) || 'all';
  if (activeGroup !== 'all' && groups.indexOf(activeGroup) === -1) activeGroup = 'all';

  var shortcuts = loadShortcuts();

  // ---- Toast with undo ----
  var toastEl = document.getElementById('toast');
  var toastMsg = document.getElementById('toastMsg');
  var toastAction = document.getElementById('toastAction');
  var toastTimer = null;
  var undoFn = null;

  function showToast(msg, onUndo, actionLabel) {
    toastMsg.textContent = msg;
    undoFn = onUndo || null;
    toastAction.textContent = actionLabel || 'Undo';
    toastAction.style.display = undoFn ? '' : 'none';
    toastEl.classList.add('show');
    clearTimeout(toastTimer);
    toastTimer = setTimeout(hideToast, 6000);
  }

  function hideToast() {
    toastEl.classList.remove('show');
    undoFn = null;
  }

  toastAction.addEventListener('click', function () {
    if (undoFn) undoFn();
    hideToast();
  });

  function normalizeUrl(input) {
    var v = input.trim();
    if (!v) return '';
    if (!/^https?:\/\//i.test(v)) v = 'https://' + v;
    return v;
  }

  function hostnameFor(url) {
    try { return new URL(url).hostname; } catch (e) { return ''; }
  }

  function initialFor(name) {
    return (name.trim().charAt(0) || '?').toUpperCase();
  }

  function removeShortcut(index) {
    var removed = shortcuts[index];
    shortcuts.splice(index, 1);
    saveShortcuts(shortcuts);
    renderShortcuts();
    showToast('Removed ' + removed.name, function () {
      shortcuts.splice(index, 0, removed);
      saveShortcuts(shortcuts);
      renderShortcuts();
    });
  }

  function visibleShortcuts() {
    return shortcuts
      .map(function (s, i) { return { s: s, i: i }; })
      .filter(function (e) { return activeGroup === 'all' || (e.s.group || '') === activeGroup; });
  }

  function renderGroupTabs() {
    groupTabsEl.innerHTML = '';
    groupTabsEl.classList.toggle('hidden', groups.length === 0 && !editing);

    function setActiveGroup(id) {
      activeGroup = id;
      localStorage.setItem(STORAGE_ACTIVE_GROUP, activeGroup);
      renderShortcuts();
    }

    function makeTab(id, label, removable) {
      var btn = document.createElement('button');
      btn.className = 'group-tab' + (activeGroup === id ? ' active' : '');
      var text = document.createElement('span');
      text.textContent = label;
      btn.appendChild(text);

      if (removable) {
        var rm = document.createElement('span');
        rm.className = 'group-tab-remove';
        rm.textContent = '×';
        rm.setAttribute('aria-label', 'Delete group ' + label);
        rm.addEventListener('click', function (e) {
          e.stopPropagation();
          if (!confirm('Delete group "' + label + '"? Its shortcuts will become ungrouped.')) return;
          groups = groups.filter(function (g) { return g !== id; });
          shortcuts.forEach(function (s) { if (s.group === id) s.group = ''; });
          saveShortcuts(shortcuts);
          saveGroups(groups);
          setActiveGroup(activeGroup === id ? 'all' : activeGroup);
        });
        btn.appendChild(rm);
      }

      btn.addEventListener('click', function () { setActiveGroup(id); });
      return btn;
    }

    groupTabsEl.appendChild(makeTab('all', 'All', false));
    groups.forEach(function (g) { groupTabsEl.appendChild(makeTab(g, g, true)); });

    var addTab = document.createElement('button');
    addTab.className = 'group-tab group-tab-add';
    addTab.textContent = '+';
    addTab.setAttribute('aria-label', 'Add group');
    addTab.addEventListener('click', function () {
      var name = prompt('New group name');
      if (!name) return;
      name = name.trim();
      if (!name || name === 'all' || groups.indexOf(name) > -1) return;
      groups.push(name);
      saveGroups(groups);
      setActiveGroup(name);
    });
    groupTabsEl.appendChild(addTab);
  }

  function renderShortcuts() {
    renderGroupTabs();
    grid.innerHTML = '';
    visibleShortcuts().forEach(function (entry, viewIdx) {
      var s = entry.s, i = entry.i;
      var tile = document.createElement(editing ? 'div' : 'a');
      tile.className = 'tile';
      if (!editing) {
        tile.href = s.url;
        tile.target = '_blank';
        tile.rel = 'noopener noreferrer';
      }
      tile.draggable = editing;
      tile.dataset.index = i;

      var icon = document.createElement('div');
      icon.className = 'tile-icon';
      var host = hostnameFor(s.url);
      if (host) {
        var img = document.createElement('img');
        img.src = 'https://www.google.com/s2/favicons?sz=64&domain=' + host;
        img.alt = '';
        img.onerror = function () {
          icon.innerHTML = '';
          icon.textContent = initialFor(s.name);
        };
        icon.appendChild(img);
      } else {
        icon.textContent = initialFor(s.name);
      }

      var label = document.createElement('div');
      label.className = 'tile-label';
      label.textContent = s.name;

      tile.appendChild(icon);
      tile.appendChild(label);

      if (viewIdx < 9) {
        var hk = document.createElement('div');
        hk.className = 'tile-hotkey';
        hk.textContent = viewIdx + 1;
        tile.appendChild(hk);
      }

      if (editing) {
        var removeBtn = document.createElement('button');
        removeBtn.className = 'tile-remove';
        removeBtn.textContent = '\u00d7';
        removeBtn.addEventListener('click', function (e) {
          e.stopPropagation();
          removeShortcut(i);
        });
        tile.appendChild(removeBtn);

        tile.addEventListener('click', function (e) {
          e.preventDefault();
          openModal(i);
        });

        tile.addEventListener('dragstart', function () {
          dragIndex = i;
          tile.classList.add('dragging');
        });
        tile.addEventListener('dragend', function () {
          tile.classList.remove('dragging');
        });
        tile.addEventListener('dragover', function (e) {
          e.preventDefault();
        });
        tile.addEventListener('drop', function (e) {
          e.preventDefault();
          if (dragIndex === null || dragIndex === i) return;
          var moved = shortcuts.splice(dragIndex, 1)[0];
          shortcuts.splice(i, 0, moved);
          saveShortcuts(shortcuts);
          dragIndex = null;
          renderShortcuts();
        });
      }

      grid.appendChild(tile);
    });

    var addTile = document.createElement('div');
    addTile.className = 'tile add-tile';
    var addIcon = document.createElement('div');
    addIcon.className = 'tile-icon';
    addIcon.textContent = '+';
    var addLabel = document.createElement('div');
    addLabel.className = 'tile-label';
    addLabel.textContent = 'Add';
    addTile.appendChild(addIcon);
    addTile.appendChild(addLabel);
    addTile.addEventListener('click', function () { openModal(null); });
    grid.appendChild(addTile);
  }

  function populateGroupSelect(selected) {
    tileGroupSelect.innerHTML = '<option value="">No group</option>';
    groups.forEach(function (g) {
      var opt = document.createElement('option');
      opt.value = g;
      opt.textContent = g;
      tileGroupSelect.appendChild(opt);
    });
    tileGroupSelect.value = selected || '';
  }

  function openModal(index) {
    editingIndex = index;
    if (index === null) {
      modalTitle.textContent = 'Add shortcut';
      tileNameInput.value = '';
      tileUrlInput.value = '';
      populateGroupSelect(activeGroup === 'all' ? '' : activeGroup);
      modalDelete.classList.add('hidden');
    } else {
      modalTitle.textContent = 'Edit shortcut';
      tileNameInput.value = shortcuts[index].name;
      tileUrlInput.value = shortcuts[index].url;
      populateGroupSelect(shortcuts[index].group || '');
      modalDelete.classList.remove('hidden');
    }
    modalOverlay.classList.remove('hidden');
    tileNameInput.focus();
  }

  function closeModal() {
    modalOverlay.classList.add('hidden');
    editingIndex = null;
  }

  modalCancel.addEventListener('click', closeModal);
  modalOverlay.addEventListener('click', function (e) {
    if (e.target === modalOverlay) closeModal();
  });

  modalSave.addEventListener('click', function () {
    var name = tileNameInput.value.trim();
    var url = normalizeUrl(tileUrlInput.value);
    if (!name || !url) return;

    var host = hostnameFor(url).replace(/^www\./, '');
    var dupe = shortcuts.findIndex(function (s, i) {
      return i !== editingIndex && hostnameFor(s.url).replace(/^www\./, '') === host;
    });
    if (host && dupe > -1) {
      if (!confirm(shortcuts[dupe].name + ' already points to ' + host + '. Add this anyway?')) return;
    }

    var group = tileGroupSelect.value;
    if (editingIndex === null) {
      shortcuts.push({ name: name, url: url, group: group });
    } else {
      shortcuts[editingIndex] = { name: name, url: url, group: group };
    }
    saveShortcuts(shortcuts);
    closeModal();
    renderShortcuts();
  });

  modalDelete.addEventListener('click', function () {
    if (editingIndex === null) return;
    var idx = editingIndex;
    closeModal();
    removeShortcut(idx);
  });

  editBtn.addEventListener('click', function () {
    editing = !editing;
    document.body.classList.toggle('editing', editing);
    editBtn.classList.toggle('active', editing);
    renderShortcuts();
  });

  settingsBtn.addEventListener('click', function () {
    scratchPanel.classList.add('hidden');
    scratchBtn.classList.remove('active');
    settingsPanel.classList.remove('hidden');
  });
  panelClose.addEventListener('click', function () {
    settingsPanel.classList.add('hidden');
  });

  // ---- Custom accent colors ----
  // Overrides are stored per theme, keyed by theme name, so switching
  // themes remembers whatever custom accents were set for each one.
  var isHexColor = function (v) { return typeof v === 'string' && /^#[0-9a-fA-F]{6}$/.test(v); };

  function loadColorOverrides() {
    try {
      var parsed = JSON.parse(localStorage.getItem(STORAGE_COLORS));
      return (parsed && typeof parsed === 'object') ? parsed : {};
    } catch (e) { return {}; }
  }
  var colorOverrides = loadColorOverrides();
  function saveColorOverrides() {
    localStorage.setItem(STORAGE_COLORS, JSON.stringify(colorOverrides));
  }

  function hexToRgba(hex, alpha) {
    var v = hex.replace('#', '');
    var num = parseInt(v, 16);
    return 'rgba(' + ((num >> 16) & 255) + ',' + ((num >> 8) & 255) + ',' + (num & 255) + ',' + alpha + ')';
  }

  // Accent doubles as --clock-2 and accent-2 as --clock in every built-in
  // theme, so a custom accent recolors the clock too instead of leaving it stale.
  function applyColorOverrides(theme) {
    var root = document.documentElement.style;
    var ov = colorOverrides[theme];
    if (ov && isHexColor(ov.accent)) {
      root.setProperty('--accent', ov.accent);
      root.setProperty('--clock-2', ov.accent);
      root.setProperty('--shadow', hexToRgba(ov.accent, 0.3));
    } else {
      root.removeProperty('--accent');
      root.removeProperty('--clock-2');
      root.removeProperty('--shadow');
    }
    if (ov && isHexColor(ov.accent2)) {
      root.setProperty('--accent-2', ov.accent2);
      root.setProperty('--clock', ov.accent2);
    } else {
      root.removeProperty('--accent-2');
      root.removeProperty('--clock');
    }
  }

  var colorAccentInput = document.getElementById('colorAccent');
  var colorAccent2Input = document.getElementById('colorAccent2');
  var colorResetBtn = document.getElementById('colorReset');

  function updateColorInputs() {
    var cs = getComputedStyle(document.documentElement);
    colorAccentInput.value = cs.getPropertyValue('--accent').trim();
    colorAccent2Input.value = cs.getPropertyValue('--accent-2').trim();
  }

  function updateFaviconAndMeta() {
    var cs = getComputedStyle(document.documentElement);
    var bg = cs.getPropertyValue('--bg').trim();
    var accent = cs.getPropertyValue('--accent').trim();
    var meta = document.getElementById('themeColorMeta');
    if (meta && bg) meta.setAttribute('content', bg);
    var fav = document.getElementById('favicon');
    if (fav && bg && accent) {
      fav.href = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='"
        + encodeURIComponent(bg)
        + "'/%3E%3Cpath d='M16 34 32 20l16 14v14a2 2 0 0 1-2 2H34V40h-4v10H18a2 2 0 0 1-2-2z' fill='"
        + encodeURIComponent(accent)
        + "'/%3E%3C/svg%3E";
    }
  }

  function applyTheme(theme) {
    document.documentElement.setAttribute('data-theme', theme);
    localStorage.setItem(STORAGE_THEME, theme);
    Array.prototype.forEach.call(themeGrid.children, function (btn) {
      btn.classList.toggle('active', btn.dataset.swatch === theme);
    });
    applyColorOverrides(theme);
    updateColorInputs();
    updateFaviconAndMeta();
    renderParticles(theme);
  }

  themeGrid.addEventListener('click', function (e) {
    var btn = e.target.closest('.swatch');
    if (!btn) return;
    applyTheme(btn.dataset.swatch);
  });

  function onColorInputChange(key, input) {
    return function () {
      if (!isHexColor(input.value)) return;
      var theme = document.documentElement.getAttribute('data-theme');
      colorOverrides[theme] = colorOverrides[theme] || {};
      colorOverrides[theme][key] = input.value;
      saveColorOverrides();
      applyColorOverrides(theme);
      updateFaviconAndMeta();
    };
  }
  colorAccentInput.addEventListener('input', onColorInputChange('accent', colorAccentInput));
  colorAccent2Input.addEventListener('input', onColorInputChange('accent2', colorAccent2Input));

  colorResetBtn.addEventListener('click', function () {
    var theme = document.documentElement.getAttribute('data-theme');
    delete colorOverrides[theme];
    saveColorOverrides();
    applyColorOverrides(theme);
    updateColorInputs();
    updateFaviconAndMeta();
  });

  var particlesEl = document.getElementById('particles');
  // Some effects run more than one interval (a spawner plus glyph churn, say),
  // so timers are tracked as a list and torn down together.
  var particleTimers = [];

  function addTimer(fn, ms) { particleTimers.push(setInterval(fn, ms)); }
  function stopTimers() {
    particleTimers.forEach(clearInterval);
    particleTimers = [];
  }

  function rand(min, max) { return min + Math.random() * (max - min); }
  function randInt(min, max) { return Math.floor(rand(min, max + 1)); }

  var THEME_ANIM = {
    ember:    { type: 'rise',    color: 'var(--accent-2)', size: [2, 4], duration: [6, 12],  interval: 850, seed: 6 },
    forest:   { type: 'firefly', color: 'var(--accent-2)', count: 12,    size: [2, 4] },
    noir:     { type: 'twinkle', count: 45,                size: [1, 2] },
    aurora:   { type: 'aurora',  stars: 20 },
    daybreak: { type: 'firefly', color: 'var(--accent-2)', count: 14,    size: [1.5, 3] },
    frost:    { type: 'fall',    color: '#a9c9e6',         size: [2, 4], duration: [8, 15],  interval: 750, seed: 6 },
    sunset:   { type: 'clouds' },
    bloom:    { type: 'fall',    color: 'var(--accent-2)', size: [6, 10], duration: [9, 16],  interval: 1000, seed: 5, petal: true },
    matrix:    { type: 'rain',   maxColumns: 600, length: [8, 26], duration: [6, 16], churn: 5 },
    embermatrix: { type: 'rain', maxColumns: 600, length: [8, 26], duration: [6, 16], churn: 5 },
    synthwave: { type: 'synth' },
    cosmos:    { type: 'cosmos', stars: 60, shootInterval: 5200 },
    storm:     { type: 'storm',  duration: [0.7, 1.4], interval: 60, seed: 30, flashChance: 0.45 },
    abyss:     { type: 'bubbles', size: [4, 16], duration: [9, 18], interval: 700, seed: 18, rays: 4 },
    circuit:   { type: 'circuit', traces: 14, nodes: 16 },
    terminal:  { type: 'crt' },
    festival:  { type: 'fireworks', interval: 1900, sparks: 22 },
    ripple:    { type: 'ripple', interval: 1100 },
    lava:      { type: 'lava', blobs: 6 }
  };

  function clearParticles() {
    particlesEl.innerHTML = '';
    stopTimers();
  }

  function spawnRiseOrFall(cfg, kind) {
    function spawn() {
      var p = document.createElement('div');
      p.className = kind === 'rise' ? 'ember-particle' : ('fall-particle' + (cfg.petal ? ' petal' : ''));
      var size = rand(cfg.size[0], cfg.size[1]);
      var duration = rand(cfg.duration[0], cfg.duration[1]);
      var drift = rand(-30, 30) + 'px';
      p.style.left = rand(0, 100) + 'vw';
      p.style.width = size + 'px';
      p.style.height = size + 'px';
      p.style.setProperty('--drift', drift);
      p.style.setProperty('--particle-color', cfg.color);
      if (cfg.petal) p.style.setProperty('--spin', rand(180, 540) + 'deg');
      p.style.background = cfg.color;
      p.style.boxShadow = cfg.petal ? 'none' : ('0 0 6px 1px ' + cfg.color);
      p.style.animationDuration = duration + 's';
      particlesEl.appendChild(p);
      setTimeout(function () { p.remove(); }, duration * 1000);
    }
    for (var i = 0; i < cfg.seed; i++) setTimeout(spawn, i * (cfg.interval * 0.7));
    addTimer(spawn, cfg.interval);
  }

  function spawnStars(count) {
    for (var i = 0; i < count; i++) {
      var s = document.createElement('div');
      s.className = 'star';
      var size = rand(1, 2.4);
      s.style.left = rand(0, 100) + 'vw';
      s.style.top = rand(0, 65) + 'vh';
      s.style.width = size + 'px';
      s.style.height = size + 'px';
      s.style.animationDuration = rand(2, 5) + 's';
      s.style.animationDelay = rand(0, 4) + 's';
      particlesEl.appendChild(s);
    }
  }

  function spawnFireflies(cfg) {
    for (var i = 0; i < cfg.count; i++) {
      var f = document.createElement('div');
      f.className = 'firefly';
      var size = rand(cfg.size[0], cfg.size[1]);
      f.style.left = rand(0, 100) + 'vw';
      f.style.top = rand(10, 85) + 'vh';
      f.style.width = size + 'px';
      f.style.height = size + 'px';
      f.style.setProperty('--particle-color', cfg.color);
      f.style.background = cfg.color;
      f.style.setProperty('--fx1', rand(-30, 30) + 'px');
      f.style.setProperty('--fy1', rand(-30, 30) + 'px');
      f.style.setProperty('--fx2', rand(-30, 30) + 'px');
      f.style.setProperty('--fy2', rand(-30, 30) + 'px');
      f.style.setProperty('--fx3', rand(-30, 30) + 'px');
      f.style.setProperty('--fy3', rand(-30, 30) + 'px');
      f.style.animationDuration = rand(7, 13) + 's, ' + rand(2, 4) + 's';
      f.style.animationDelay = rand(0, 4) + 's';
      particlesEl.appendChild(f);
    }
  }

  function buildClouds() {
    var count = 4;
    for (var i = 0; i < count; i++) {
      var c = document.createElement('div');
      c.className = 'cloud';
      var size = rand(140, 300);
      c.style.top = rand(4, 34) + 'vh';
      c.style.width = size + 'px';
      c.style.height = size * 0.5 + 'px';
      c.style.animationDuration = rand(45, 80) + 's';
      c.style.animationDelay = '-' + rand(0, 60) + 's';
      particlesEl.appendChild(c);
    }
  }

  function buildAurora() {
    var colors = ['var(--accent)', 'var(--accent-2)', 'var(--accent)'];
    for (var i = 0; i < 3; i++) {
      var b = document.createElement('div');
      b.className = 'aurora-blob';
      var size = rand(260, 420);
      b.style.width = size + 'px';
      b.style.height = size + 'px';
      b.style.left = rand(-10, 70) + 'vw';
      b.style.top = rand(-10, 20) + 'vh';
      b.style.background = colors[i];
      b.style.opacity = 0.35;
      b.style.animationDuration = rand(14, 22) + 's';
      b.style.animationDelay = '-' + rand(0, 15) + 's';
      particlesEl.appendChild(b);
    }
  }

  // Half-width katakana, the glyphs the film's rain is built from, plus digits.
  var RAIN_GLYPHS = 'ｱｲｳｴｵｶｷｸｹｺｻｼｽｾｿﾀﾁﾂﾃﾄﾅﾆﾇﾈﾉﾊﾋﾌﾍﾎﾏﾐﾑﾒﾓﾔﾕﾖﾗﾘﾙﾚﾛﾜﾝ0123456789';

  function randGlyph() {
    return RAIN_GLYPHS.charAt(Math.floor(Math.random() * RAIN_GLYPHS.length));
  }

  function buildRain(cfg) {
    var colWidth = 10;
    var cols = Math.min(cfg.maxColumns, Math.ceil(window.innerWidth / colWidth));
    var columns = [];

    for (var i = 0; i < cols; i++) {
      var col = document.createElement('div');
      col.className = 'rain-column';
      col.style.left = (i * colWidth) + 'px';
      col.style.animationDuration = rand(cfg.duration[0], cfg.duration[1]) + 's';
      // Negative delays start each column mid-fall, so nothing lines up.
      col.style.animationDelay = '-' + rand(0, 14) + 's';
      col.style.opacity = rand(0.3, 0.62);

      var len = randInt(cfg.length[0], cfg.length[1]);
      var glyphs = [];
      for (var j = 0; j < len; j++) glyphs.push(randGlyph());
      col.dataset.len = len;
      paintColumn(col, glyphs);
      col._glyphs = glyphs;

      particlesEl.appendChild(col);
      columns.push(col);
    }

    // Churn a few glyphs per frame-ish rather than redrawing every column.
    addTimer(function () {
      for (var n = 0; n < cfg.churn; n++) {
        var col = columns[Math.floor(Math.random() * columns.length)];
        if (!col || !col._glyphs) continue;
        col._glyphs[Math.floor(Math.random() * col._glyphs.length)] = randGlyph();
        paintColumn(col, col._glyphs);
      }
    }, 120);
  }

  function paintColumn(col, glyphs) {
    var body = glyphs.slice(0, -1).join('\n');
    col.innerHTML = '';
    col.appendChild(document.createTextNode(body + '\n'));
    var head = document.createElement('span');
    head.className = 'rain-head';
    head.textContent = glyphs[glyphs.length - 1];
    col.appendChild(head);
  }

  function buildSynthwave() {
    var sun = document.createElement('div');
    sun.className = 'synth-sun';
    particlesEl.appendChild(sun);
    var grid = document.createElement('div');
    grid.className = 'synth-grid';
    particlesEl.appendChild(grid);
  }

  function buildCosmos(cfg) {
    spawnStars(cfg.stars);
    for (var i = 0; i < 2; i++) {
      var b = document.createElement('div');
      b.className = 'aurora-blob';
      var size = rand(300, 460);
      b.style.width = size + 'px';
      b.style.height = size + 'px';
      b.style.left = rand(-5, 65) + 'vw';
      b.style.top = rand(-15, 25) + 'vh';
      b.style.background = i === 0 ? 'var(--accent)' : 'var(--accent-2)';
      b.style.opacity = 0.22;
      b.style.animationDuration = rand(20, 30) + 's';
      b.style.animationDelay = '-' + rand(0, 20) + 's';
      particlesEl.appendChild(b);
    }
    addTimer(function () {
      var s = document.createElement('div');
      s.className = 'shooting-star';
      s.style.left = rand(-10, 45) + 'vw';
      s.style.top = rand(2, 40) + 'vh';
      var dur = rand(0.9, 1.6);
      s.style.animationDuration = dur + 's';
      particlesEl.appendChild(s);
      setTimeout(function () { s.remove(); }, dur * 1000);
    }, cfg.shootInterval);
  }

  function buildStorm(cfg) {
    function spawn() {
      var s = document.createElement('div');
      s.className = 'rain-streak';
      var duration = rand(cfg.duration[0], cfg.duration[1]);
      s.style.left = rand(0, 120) + 'vw';
      s.style.height = rand(40, 90) + 'px';
      s.style.setProperty('--drift', rand(-16, -10) + 'vw');
      s.style.animationDuration = duration + 's';
      particlesEl.appendChild(s);
      setTimeout(function () { s.remove(); }, duration * 1000);
    }
    for (var i = 0; i < cfg.seed; i++) setTimeout(spawn, i * 60);
    addTimer(spawn, cfg.interval);

    addTimer(function () {
      if (Math.random() > cfg.flashChance) return;
      var f = document.createElement('div');
      f.className = 'lightning';
      particlesEl.appendChild(f);
      setTimeout(function () { f.remove(); }, 260);
    }, 3000);
  }

  function buildAbyss(cfg) {
    for (var r = 0; r < cfg.rays; r++) {
      var ray = document.createElement('div');
      ray.className = 'water-ray';
      ray.style.left = rand(0, 95) + 'vw';
      ray.style.animationDuration = rand(9, 16) + 's';
      ray.style.animationDelay = '-' + rand(0, 10) + 's';
      particlesEl.appendChild(ray);
    }
    // A bubble takes up to 18s to cross, so the seeded ones start mid-climb via
    // a negative delay -- otherwise the water is empty for the first while.
    function spawn(preroll) {
      var b = document.createElement('div');
      b.className = 'bubble';
      var size = rand(cfg.size[0], cfg.size[1]);
      var duration = rand(cfg.duration[0], cfg.duration[1]);
      var offset = preroll === true ? rand(0, duration) : 0;
      b.style.left = rand(0, 100) + 'vw';
      b.style.width = size + 'px';
      b.style.height = size + 'px';
      b.style.setProperty('--wobble', rand(-28, 28) + 'px');
      b.style.animationDuration = duration + 's';
      if (offset) b.style.animationDelay = '-' + offset + 's';
      particlesEl.appendChild(b);
      setTimeout(function () { b.remove(); }, (duration - offset) * 1000);
    }
    for (var i = 0; i < cfg.seed; i++) spawn(true);
    addTimer(spawn, cfg.interval);
  }

  var SVG_NS = 'http://www.w3.org/2000/svg';

  // Builds an orthogonal trace: a few right-angle segments, like a PCB track.
  function tracePath(w, h) {
    var x = Math.random() < 0.5 ? 0 : w;
    var y = rand(0, h);
    var d = 'M' + x.toFixed(1) + ' ' + y.toFixed(1);
    var dir = x === 0 ? 1 : -1;
    var segments = randInt(3, 6);
    var pts = [];
    for (var i = 0; i < segments; i++) {
      x += dir * rand(w * 0.08, w * 0.22);
      d += ' L' + x.toFixed(1) + ' ' + y.toFixed(1);
      y += (Math.random() < 0.5 ? -1 : 1) * rand(h * 0.04, h * 0.16);
      d += ' L' + x.toFixed(1) + ' ' + y.toFixed(1);
      pts.push([x, y]);
    }
    return { d: d, points: pts };
  }

  function buildCircuit(cfg) {
    var w = window.innerWidth;
    var h = window.innerHeight;
    var svg = document.createElementNS(SVG_NS, 'svg');
    svg.setAttribute('class', 'circuit-svg');
    svg.setAttribute('viewBox', '0 0 ' + w + ' ' + h);
    var joints = [];
    var pulses = [];

    for (var i = 0; i < cfg.traces; i++) {
      var t = tracePath(w, h);
      joints = joints.concat(t.points);

      var base = document.createElementNS(SVG_NS, 'path');
      base.setAttribute('class', 'circuit-trace');
      base.setAttribute('d', t.d);
      svg.appendChild(base);

      var pulse = document.createElementNS(SVG_NS, 'path');
      pulse.setAttribute('class', 'circuit-pulse');
      pulse.setAttribute('d', t.d);
      svg.appendChild(pulse);

      // getTotalLength needs the node in the document, so measure after append.
      pulses.push(pulse);
    }

    particlesEl.appendChild(svg);

    pulses.forEach(function (p) {
      var len = p.getTotalLength();
      var dash = 55;
      p.style.strokeDasharray = dash + ' ' + len;
      p.style.setProperty('--dash', -(len + dash) + 'px');
      p.style.animationDuration = rand(3, 8) + 's';
      p.style.animationDelay = '-' + rand(0, 6) + 's';
    });

    for (var n = 0; n < cfg.nodes && n < joints.length; n++) {
      var j = joints[Math.floor(Math.random() * joints.length)];
      var c = document.createElementNS(SVG_NS, 'circle');
      c.setAttribute('class', 'circuit-node');
      c.setAttribute('cx', j[0]);
      c.setAttribute('cy', j[1]);
      c.setAttribute('r', rand(2, 3.5));
      c.style.animationDuration = rand(2, 5) + 's';
      c.style.animationDelay = '-' + rand(0, 4) + 's';
      svg.appendChild(c);
    }
  }

  function buildCrt() {
    ['crt-glow', 'crt-scanlines', 'crt-roll', 'crt-vignette'].forEach(function (cls) {
      var el = document.createElement('div');
      el.className = cls;
      particlesEl.appendChild(el);
    });
  }

  var FIREWORK_COLORS = ['#ffd166', '#ef476f', '#06d6a0', '#8ecae6', '#c77dff', '#ff9f1c'];

  function buildFireworks(cfg) {
    function burst(x, y, color) {
      var flash = document.createElement('div');
      flash.className = 'burst-flash';
      flash.style.left = x + 'px';
      flash.style.top = y + 'px';
      flash.style.setProperty('--spark-color', color);
      particlesEl.appendChild(flash);
      setTimeout(function () { flash.remove(); }, 430);

      for (var i = 0; i < cfg.sparks; i++) {
        var angle = (Math.PI * 2 * i) / cfg.sparks + rand(-0.12, 0.12);
        var dist = rand(75, 175);
        var s = document.createElement('div');
        s.className = 'spark';
        s.style.left = x + 'px';
        s.style.top = y + 'px';
        s.style.setProperty('--dx', Math.cos(angle) * dist + 'px');
        s.style.setProperty('--dy', Math.sin(angle) * dist + 'px');
        s.style.setProperty('--spark-color', color);
        var dur = rand(1.1, 1.8);
        s.style.animationDuration = dur + 's';
        particlesEl.appendChild(s);
        (function (el, ms) { setTimeout(function () { el.remove(); }, ms); })(s, dur * 1000);
      }
    }

    function launch() {
      var color = FIREWORK_COLORS[Math.floor(Math.random() * FIREWORK_COLORS.length)];
      var x = rand(window.innerWidth * 0.12, window.innerWidth * 0.88);
      var peak = rand(window.innerHeight * 0.12, window.innerHeight * 0.45);
      var climb = window.innerHeight - peak;
      var r = document.createElement('div');
      r.className = 'rocket';
      r.style.left = x + 'px';
      r.style.top = window.innerHeight + 'px';
      r.style.setProperty('--climb', -climb + 'px');
      r.style.setProperty('--spark-color', color);
      var climbMs = rand(900, 1300);
      r.style.animationDuration = climbMs + 'ms';
      particlesEl.appendChild(r);
      setTimeout(function () { r.remove(); burst(x, peak, color); }, climbMs);
    }

    launch();
    addTimer(launch, cfg.interval);
  }

  function buildRipple(cfg) {
    function drop() {
      var x = rand(5, 95);
      var y = rand(8, 92);
      // Two rings offset in time read as one spreading disturbance.
      for (var i = 0; i < 2; i++) {
        var ring = document.createElement('div');
        ring.className = 'ripple-ring';
        var size = rand(160, 340);
        var dur = rand(2.8, 4.4);
        ring.style.left = x + 'vw';
        ring.style.top = y + 'vh';
        ring.style.setProperty('--r', size + 'px');
        ring.style.animationDuration = dur + 's';
        ring.style.animationDelay = (i * 0.35) + 's';
        particlesEl.appendChild(ring);
        (function (el, ms) { setTimeout(function () { el.remove(); }, ms); })(ring, (dur + i * 0.35) * 1000 + 100);
      }
    }
    drop();
    addTimer(drop, cfg.interval);
  }

  function buildLava(cfg) {
    var defs = document.createElementNS(SVG_NS, 'svg');
    defs.setAttribute('width', '0');
    defs.setAttribute('height', '0');
    defs.style.position = 'absolute';
    defs.innerHTML =
      '<defs><filter id="goo">' +
      '<feGaussianBlur in="SourceGraphic" stdDeviation="16" result="blur"/>' +
      '<feColorMatrix in="blur" mode="matrix" ' +
      'values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo"/>' +
      '<feBlend in="SourceGraphic" in2="goo"/>' +
      '</filter></defs>';
    particlesEl.appendChild(defs);

    var field = document.createElement('div');
    field.className = 'lava-field';
    for (var i = 0; i < cfg.blobs; i++) {
      var b = document.createElement('div');
      b.className = 'lava-blob';
      var size = rand(90, 190);
      b.style.width = size + 'px';
      b.style.height = size + 'px';
      b.style.left = rand(2, 88) + 'vw';
      b.style.bottom = rand(-20, 10) + 'vh';
      b.style.background = i % 2 ? 'var(--accent-2)' : 'var(--accent)';
      b.style.animationDuration = rand(14, 26) + 's';
      b.style.animationDelay = '-' + rand(0, 14) + 's';
      field.appendChild(b);
    }
    particlesEl.appendChild(field);
  }

  function renderParticles(theme) {
    clearParticles();
    var cfg = THEME_ANIM[theme];
    if (!cfg) return;
    if (cfg.type === 'rise' || cfg.type === 'fall') spawnRiseOrFall(cfg, cfg.type);
    else if (cfg.type === 'twinkle') spawnStars(cfg.count);
    else if (cfg.type === 'firefly') spawnFireflies(cfg);
    else if (cfg.type === 'clouds') buildClouds();
    else if (cfg.type === 'aurora') { buildAurora(); spawnStars(cfg.stars); }
    else if (cfg.type === 'rain') buildRain(cfg);
    else if (cfg.type === 'synth') buildSynthwave();
    else if (cfg.type === 'cosmos') buildCosmos(cfg);
    else if (cfg.type === 'storm') buildStorm(cfg);
    else if (cfg.type === 'bubbles') buildAbyss(cfg);
    else if (cfg.type === 'circuit') buildCircuit(cfg);
    else if (cfg.type === 'crt') buildCrt();
    else if (cfg.type === 'fireworks') buildFireworks(cfg);
    else if (cfg.type === 'ripple') buildRipple(cfg);
    else if (cfg.type === 'lava') buildLava(cfg);
  }

  function greetingFor(hour) {
    if (hour >= 5 && hour < 12) return 'Good morning';
    if (hour >= 12 && hour < 17) return 'Good afternoon';
    if (hour >= 17 && hour < 21) return 'Good evening';
    return 'Good night';
  }

  // Set to false for a 12-hour clock with an AM/PM suffix.
  var CLOCK_24H = true;

  function pad2(n) { return (n < 10 ? '0' : '') + n; }

  // ISO-8601 week number: week 1 is the one holding the year's first Thursday.
  function isoWeek(d) {
    var t = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
    t.setUTCDate(t.getUTCDate() + 4 - (t.getUTCDay() || 7));
    var yearStart = Date.UTC(t.getUTCFullYear(), 0, 1);
    return Math.ceil(((t - yearStart) / 86400000 + 1) / 7);
  }

  function dayOfYear(d) {
    return Math.floor((d - new Date(d.getFullYear(), 0, 0)) / 86400000);
  }

  function utcOffset(d) {
    var mins = -d.getTimezoneOffset();
    var sign = mins < 0 ? '-' : '+';
    mins = Math.abs(mins);
    return sign + pad2(Math.floor(mins / 60)) + ':' + pad2(mins % 60);
  }

  var clockH = document.getElementById('clockH');
  var clockM = document.getElementById('clockM');
  var clockS = document.getElementById('clockS');
  var clockMeter = document.getElementById('clockMeter');
  var clockGhost = document.querySelector('.clock-ghost');
  var lastDateKey = '';
  var lastGreeting = '';

  function tick() {
    var now = new Date();
    var h = now.getHours();
    var m = now.getMinutes();
    var s = now.getSeconds();

    var shown = CLOCK_24H ? h : (h % 12 === 0 ? 12 : h % 12);
    clockH.textContent = CLOCK_24H ? pad2(shown) : String(shown);
    clockM.textContent = pad2(m);
    clockS.textContent = pad2(s) + (CLOCK_24H ? '' : (h < 12 ? ' AM' : ' PM'));
    clockGhost.textContent = (CLOCK_24H || shown >= 10) ? '88:88' : '8:88';

    // Skip the sweep animation across the :59 -> :00 wrap so it doesn't run backwards.
    clockMeter.classList.toggle('no-anim', s === 0);
    clockMeter.style.width = (s / 60 * 100) + '%';

    var greeting = greetingFor(h);
    if (greeting !== lastGreeting) {
      lastGreeting = greeting;
      document.getElementById('greeting').textContent = greeting;
    }

    var dateKey = now.toDateString();
    if (dateKey === lastDateKey) return;
    lastDateKey = dateKey;

    var days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
    var months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
    document.getElementById('date').textContent = days[now.getDay()] + ', ' + months[now.getMonth()] + ' ' + now.getDate();

    document.getElementById('metaIso').textContent =
      now.getFullYear() + '-' + pad2(now.getMonth() + 1) + '-' + pad2(now.getDate());
    document.getElementById('metaWeek').textContent = pad2(isoWeek(now));
    document.getElementById('metaDoy').textContent = dayOfYear(now);
    document.getElementById('metaTz').textContent = 'UTC' + utcOffset(now);
  }

  var clockTimer = null;
  function startClock() {
    tick();
    if (!clockTimer) clockTimer = setInterval(tick, 1000);
  }
  function stopClock() {
    if (clockTimer) { clearInterval(clockTimer); clockTimer = null; }
  }

  startClock();

  var savedEngine = localStorage.getItem(STORAGE_ENGINE);
  if (savedEngine) engineSelect.value = savedEngine;
  engineSelect.addEventListener('change', function () {
    localStorage.setItem(STORAGE_ENGINE, engineSelect.value);
  });

  // ---- Launcher ----
  var resultsEl = document.getElementById('results');
  var matches = [];
  var selectedIdx = 0;

  var COMMANDS = [
    { prefix: 'g',  label: 'Google',        url: 'https://www.google.com/search?q=' },
    { prefix: 'd',  label: 'DuckDuckGo',    url: 'https://duckduckgo.com/?q=' },
    { prefix: 'y',  label: 'YouTube',       url: 'https://www.youtube.com/results?search_query=' },
    { prefix: 'gh', label: 'GitHub',        url: 'https://github.com/search?q=' },
    { prefix: 'w',  label: 'Wikipedia',     url: 'https://en.wikipedia.org/w/index.php?search=' },
    { prefix: 'r',  label: 'Reddit',        url: 'https://www.reddit.com/search/?q=' },
    { prefix: 'a',  label: 'Amazon',        url: 'https://www.amazon.com/s?k=' },
    { prefix: 'm',  label: 'Maps',          url: 'https://www.google.com/maps/search/' },
    { prefix: 'i',  label: 'Images',        url: 'https://www.google.com/search?tbm=isch&q=' },
    { prefix: 'np', label: 'npm',           url: 'https://www.npmjs.com/search?q=' },
    { prefix: 'mdn',label: 'MDN',           url: 'https://developer.mozilla.org/en-US/search?q=' },
    { prefix: 'so', label: 'Stack Overflow',url: 'https://stackoverflow.com/search?q=' }
  ];

  function parseCommand(q) {
    var m = q.match(/^(\S+)\s+(.*)$/);
    if (!m) return null;
    var cmd = COMMANDS.find(function (c) { return c.prefix === m[1].toLowerCase(); });
    if (!cmd || !m[2].trim()) return null;
    return { cmd: cmd, term: m[2].trim() };
  }

  function partialCommands(q) {
    var v = q.trim().toLowerCase();
    if (!v || /\s/.test(v)) return [];
    return COMMANDS.filter(function (c) { return c.prefix.indexOf(v) === 0; });
  }

  function scoreMatch(shortcut, q) {
    var name = shortcut.name.toLowerCase();
    var host = hostnameFor(shortcut.url).toLowerCase().replace(/^www\./, '');
    if (name === q || host === q) return 0;
    if (name.indexOf(q) === 0) return 1;
    if (host.indexOf(q) === 0) return 2;
    if (name.indexOf(q) > -1) return 3;
    if (host.indexOf(q) > -1) return 4;
    return -1;
  }

  function computeMatches(q) {
    q = q.trim().toLowerCase();
    if (!q) return [];
    return shortcuts
      .map(function (s, i) { return { s: s, i: i, score: scoreMatch(s, q) }; })
      .filter(function (m) { return m.score > -1; })
      .sort(function (a, b) { return a.score - b.score; })
      .slice(0, 6)
      .map(function (m) { return m.s; });
  }

  function looksLikeUrl(q) {
    var v = q.trim();
    if (/\s/.test(v)) return false;
    return /^https?:\/\//i.test(v) || /^[\w-]+(\.[\w-]+)+(\/.*)?$/.test(v);
  }

  // ---- Inline calculator & unit conversion ----
  // A small hand-rolled recursive-descent parser rather than eval(), so a
  // typo can't run arbitrary script and behavior stays fully predictable.
  function evalMath(expr) {
    var pos = 0;
    function skipWs() { while (expr.charAt(pos) === ' ') pos++; }
    function parseNumber() {
      skipWs();
      var start = pos;
      var hasDigits = false;
      while (/[0-9]/.test(expr.charAt(pos))) { pos++; hasDigits = true; }
      if (expr.charAt(pos) === '.') {
        pos++;
        while (/[0-9]/.test(expr.charAt(pos))) { pos++; hasDigits = true; }
      }
      if (!hasDigits) throw new Error('bad number');
      return parseFloat(expr.slice(start, pos));
    }
    function parseAtom() {
      skipWs();
      var ch = expr.charAt(pos);
      if (ch === '(') {
        pos++;
        var v = parseExpr();
        skipWs();
        if (expr.charAt(pos) !== ')') throw new Error('expected )');
        pos++;
        return v;
      }
      if (ch === '-' || ch === '+') {
        pos++;
        var v2 = parseAtom();
        return ch === '-' ? -v2 : v2;
      }
      return parseNumber();
    }
    function parsePow() {
      var base = parseAtom();
      skipWs();
      if (expr.charAt(pos) === '^') {
        pos++;
        return Math.pow(base, parsePow());
      }
      return base;
    }
    function parseTerm() {
      var v = parsePow();
      for (;;) {
        skipWs();
        var op = expr.charAt(pos);
        if (op === '*' || op === '/' || op === '%') {
          pos++;
          var rhs = parsePow();
          if (op === '*') v *= rhs;
          else if (op === '/') v /= rhs;
          else v = v % rhs;
        } else break;
      }
      return v;
    }
    function parseExpr() {
      var v = parseTerm();
      for (;;) {
        skipWs();
        var op = expr.charAt(pos);
        if (op === '+' || op === '-') {
          pos++;
          var rhs = parseTerm();
          v = op === '+' ? v + rhs : v - rhs;
        } else break;
      }
      return v;
    }
    var result = parseExpr();
    skipWs();
    if (pos !== expr.length) throw new Error('trailing input');
    if (!isFinite(result)) throw new Error('not finite');
    return result;
  }

  function looksLikeMath(q) {
    var v = q.trim();
    if (!v) return false;
    if (!/^[-+*/^%().\d\s]+$/.test(v)) return false;
    if (!/\d/.test(v)) return false;
    // Bare digit-hyphen-digit is far more likely a phone number or a date
    // (555-1234, 2026-08-08) than subtraction, so don't treat it as math.
    if (/^\d+(-\d+)+$/.test(v)) return false;
    if (!/[-+*/^%]/.test(v.replace(/^-/, ''))) return false;
    return true;
  }

  function formatNum(n, decimals) {
    var factor = Math.pow(10, decimals == null ? 6 : decimals);
    if (Math.abs(n) < 1e-9) n = 0;
    var rounded = Math.round(n * factor) / factor;
    return rounded.toString();
  }

  var UNIT_ALIASES = {
    mm: 'mm', millimeter: 'mm', millimeters: 'mm', millimetre: 'mm', millimetres: 'mm',
    cm: 'cm', centimeter: 'cm', centimeters: 'cm', centimetre: 'cm', centimetres: 'cm',
    m: 'm', meter: 'm', meters: 'm', metre: 'm', metres: 'm',
    km: 'km', kilometer: 'km', kilometers: 'km', kilometre: 'km', kilometres: 'km',
    in: 'in', inch: 'in', inches: 'in',
    ft: 'ft', foot: 'ft', feet: 'ft',
    yd: 'yd', yard: 'yd', yards: 'yd',
    mi: 'mi', mile: 'mi', miles: 'mi',
    mg: 'mg', milligram: 'mg', milligrams: 'mg',
    g: 'g', gram: 'g', grams: 'g',
    kg: 'kg', kilogram: 'kg', kilograms: 'kg',
    oz: 'oz', ounce: 'oz', ounces: 'oz',
    lb: 'lb', lbs: 'lb', pound: 'lb', pounds: 'lb',
    st: 'st', stone: 'st', stones: 'st',
    ml: 'ml', milliliter: 'ml', milliliters: 'ml', millilitre: 'ml', millilitres: 'ml',
    l: 'l', liter: 'l', liters: 'l', litre: 'l', litres: 'l',
    cup: 'cup', cups: 'cup',
    tbsp: 'tbsp', tablespoon: 'tbsp', tablespoons: 'tbsp',
    tsp: 'tsp', teaspoon: 'tsp', teaspoons: 'tsp',
    floz: 'floz',
    gal: 'gal', gallon: 'gal', gallons: 'gal',
    qt: 'qt', quart: 'qt', quarts: 'qt',
    pt: 'pt', pint: 'pt', pints: 'pt',
    c: 'c', celsius: 'c',
    f: 'f', fahrenheit: 'f',
    k: 'k', kelvin: 'k'
  };
  var UNIT_TO_BASE = {
    mm: 0.001, cm: 0.01, m: 1, km: 1000, in: 0.0254, ft: 0.3048, yd: 0.9144, mi: 1609.344,
    mg: 0.001, g: 1, kg: 1000, oz: 28.3495, lb: 453.592, st: 6350.29,
    ml: 1, l: 1000, cup: 236.588, tbsp: 14.7868, tsp: 4.92892, floz: 29.5735, gal: 3785.41, qt: 946.353, pt: 473.176
  };
  var UNIT_CATEGORY = {
    mm: 'length', cm: 'length', m: 'length', km: 'length', in: 'length', ft: 'length', yd: 'length', mi: 'length',
    mg: 'weight', g: 'weight', kg: 'weight', oz: 'weight', lb: 'weight', st: 'weight',
    ml: 'volume', l: 'volume', cup: 'volume', tbsp: 'volume', tsp: 'volume', floz: 'volume', gal: 'volume', qt: 'volume', pt: 'volume',
    c: 'temp', f: 'temp', k: 'temp'
  };

  function convertTemp(v, from, to) {
    var celsius = from === 'c' ? v : from === 'f' ? (v - 32) * 5 / 9 : v - 273.15;
    if (to === 'c') return celsius;
    if (to === 'f') return celsius * 9 / 5 + 32;
    return celsius + 273.15;
  }

  function tryConvert(q) {
    var m = q.trim().match(/^(-?[\d.]+)\s*°?([a-zA-Z]+)\s+(?:to|in|as)\s+°?([a-zA-Z]+)\s*$/i);
    if (!m) return null;
    var value = parseFloat(m[1]);
    var from = UNIT_ALIASES[m[2].toLowerCase()];
    var to = UNIT_ALIASES[m[3].toLowerCase()];
    if (!from || !to) return null;
    var cat = UNIT_CATEGORY[from];
    if (cat !== UNIT_CATEGORY[to]) return null;
    var result = cat === 'temp' ? convertTemp(value, from, to) : value * UNIT_TO_BASE[from] / UNIT_TO_BASE[to];
    if (!isFinite(result)) return null;
    return { value: result, to: to };
  }

  function tryPercentOf(q) {
    var m = q.trim().match(/^(-?[\d.]+)\s*%\s+of\s+(-?[\d.]+)$/i);
    if (!m) return null;
    var result = (parseFloat(m[1]) / 100) * parseFloat(m[2]);
    return isFinite(result) ? result : null;
  }

  function computeCalc(q) {
    var pct = tryPercentOf(q);
    if (pct !== null) return { display: formatNum(pct) };
    if (looksLikeMath(q)) {
      try { return { display: formatNum(evalMath(q.trim())) }; } catch (e) { return null; }
    }
    var conv = tryConvert(q);
    if (conv) return { display: formatNum(conv.value, 2) + ' ' + conv.to };
    return null;
  }

  function copyText(str) {
    function legacyCopy() {
      var ta = document.createElement('textarea');
      ta.value = str;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      try { document.execCommand('copy'); } catch (e) {}
      document.body.removeChild(ta);
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(str).catch(legacyCopy);
    } else {
      legacyCopy();
    }
  }

  function renderResults() {
    var q = searchInput.value;
    resultsEl.innerHTML = '';
    searchForm.classList.toggle('has-value', !!q);

    if (!q.trim()) {
      resultsEl.classList.add('hidden');
      matches = [];
      return;
    }

    var rows = [];
    var parsed = parseCommand(q);

    if (!parsed) {
      var calc = computeCalc(q);
      if (calc) rows.push({ kind: 'calc', label: calc.display, sub: q.trim(), copyValue: calc.display });
    }

    if (parsed) {
      rows.push({
        kind: 'command',
        label: parsed.term,
        sub: 'on ' + parsed.cmd.label,
        prefix: parsed.cmd.prefix,
        url: parsed.cmd.url + encodeURIComponent(parsed.term)
      });
    }

    matches = computeMatches(q);
    matches.forEach(function (s) {
      rows.push({ kind: 'shortcut', label: s.name, url: s.url });
    });

    partialCommands(q).forEach(function (c) {
      rows.push({ kind: 'hint', label: 'Search ' + c.label, prefix: c.prefix, hint: true });
    });

    if (!parsed) {
      if (looksLikeUrl(q)) {
        rows.push({ kind: 'open', label: q.trim(), url: normalizeUrl(q) });
      }
      rows.push({
        kind: 'search',
        label: q.trim(),
        url: engineSelect.value + encodeURIComponent(q.trim())
      });
    }

    if (selectedIdx >= rows.length) selectedIdx = 0;

    rows.forEach(function (row, i) {
      var el = document.createElement('div');
      el.className = 'result' + (i === selectedIdx ? ' selected' : '');

      if (row.kind === 'shortcut') {
        var host = hostnameFor(row.url);
        var img = document.createElement('img');
        img.src = 'https://www.google.com/s2/favicons?sz=64&domain=' + host;
        img.alt = '';
        img.onerror = function () {
          var fb = document.createElement('div');
          fb.className = 'result-fallback';
          fb.textContent = initialFor(row.label);
          img.replaceWith(fb);
        };
        el.appendChild(img);
      } else {
        var glyph = document.createElement('div');
        glyph.className = 'result-fallback';
        glyph.textContent = row.kind === 'open' ? '\u2197' : row.kind === 'calc' ? '=' : '\u2315';
        el.appendChild(glyph);
      }

      var text = document.createElement('div');
      text.className = 'result-text';
      text.textContent = row.label;
      if (row.sub) {
        var sub = document.createElement('span');
        sub.className = 'result-host';
        sub.textContent = row.sub;
        text.appendChild(sub);
      }
      el.appendChild(text);

      if (row.prefix) {
        var pf = document.createElement('div');
        pf.className = 'result-prefix';
        pf.textContent = row.prefix + ' \u2026';
        el.appendChild(pf);
      }

      var kind = document.createElement('div');
      kind.className = 'result-kind';
      kind.textContent = row.kind === 'shortcut' ? 'Shortcut'
        : row.kind === 'open' ? 'Open'
        : row.kind === 'hint' ? 'Command'
        : row.kind === 'command' ? 'Go'
        : row.kind === 'calc' ? 'Copy'
        : 'Search';
      el.appendChild(kind);

      el.addEventListener('mouseenter', function () {
        selectedIdx = i;
        Array.prototype.forEach.call(resultsEl.children, function (c, ci) {
          c.classList.toggle('selected', ci === i);
        });
      });

      el.addEventListener('click', function () {
        if (row.hint) {
          searchInput.value = row.prefix + ' ';
          selectedIdx = 0;
          searchInput.focus();
          renderResults();
        } else if (row.kind === 'calc') {
          copyText(row.copyValue);
          showToast('Copied ' + row.copyValue);
        } else {
          go(row.url);
        }
      });

      resultsEl.appendChild(el);
    });

    resultsEl.classList.remove('hidden');
  }

  function go(url) {
    window.open(url, '_blank', 'noopener');
  }

  function activateSelection() {
    var rows = resultsEl.children;
    if (!rows.length) {
      var q = searchInput.value.trim();
      if (q) go(engineSelect.value + encodeURIComponent(q));
      return;
    }
    rows[selectedIdx] && rows[selectedIdx].click();
  }

  function moveSelection(delta) {
    var count = resultsEl.children.length;
    if (!count) return;
    selectedIdx = (selectedIdx + delta + count) % count;
    Array.prototype.forEach.call(resultsEl.children, function (c, ci) {
      c.classList.toggle('selected', ci === selectedIdx);
    });
    var sel = resultsEl.children[selectedIdx];
    if (sel && sel.scrollIntoView) sel.scrollIntoView({ block: 'nearest' });
  }

  searchInput.addEventListener('input', function () {
    selectedIdx = 0;
    renderResults();
  });

  function clearSearch() {
    searchInput.value = '';
    selectedIdx = 0;
    renderResults();
    searchInput.focus();
  }

  searchClear.addEventListener('click', clearSearch);

  searchInput.addEventListener('keydown', function (e) {
    if (e.key === 'ArrowDown') { e.preventDefault(); moveSelection(1); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); moveSelection(-1); }
  });

  searchInput.addEventListener('focus', renderResults);

  searchInput.addEventListener('blur', function () {
    setTimeout(function () { resultsEl.classList.add('hidden'); }, 150);
  });

  engineSelect.addEventListener('change', renderResults);

  searchForm.addEventListener('submit', function (e) {
    e.preventDefault();
    activateSelection();
  });

  document.addEventListener('keyup', function (e) {
    if (e.key === 'Alt') document.body.classList.remove('show-hotkeys');
  });
  window.addEventListener('blur', function () {
    document.body.classList.remove('show-hotkeys');
  });

  // Column-based effects size themselves to the viewport at build time, so a
  // resize needs a rebuild or the new width stays empty.
  var resizeTimer = null;
  window.addEventListener('resize', function () {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(function () {
      if (document.hidden) return;
      renderParticles(document.documentElement.getAttribute('data-theme'));
    }, 250);
  });

  // ---- Pause background animation and the clock when the tab isn't visible ----
  document.addEventListener('visibilitychange', function () {
    if (document.hidden) {
      stopClock();
      stopTimers();
      particlesEl.style.animationPlayState = 'paused';
      particlesEl.querySelectorAll('*').forEach(function (el) {
        el.style.animationPlayState = 'paused';
      });
    } else {
      startClock();
      renderParticles(document.documentElement.getAttribute('data-theme'));
    }
  });

  // ---- Installable app manifest ----
  (function () {
    var icon = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='%230a0606'/%3E%3Cpath d='M16 34 32 20l16 14v14a2 2 0 0 1-2 2H34V40h-4v10H18a2 2 0 0 1-2-2z' fill='%23e0362b'/%3E%3C/svg%3E";
    var manifest = {
      name: 'Home',
      short_name: 'Home',
      description: 'A custom browser home page.',
      start_url: '.',
      display: 'standalone',
      background_color: '#0a0606',
      theme_color: '#0a0606',
      icons: [
        { src: icon, sizes: 'any', type: 'image/svg+xml', purpose: 'any' }
      ]
    };
    try {
      var blob = new Blob([JSON.stringify(manifest)], { type: 'application/manifest+json' });
      var link = document.createElement('link');
      link.rel = 'manifest';
      link.href = URL.createObjectURL(blob);
      document.head.appendChild(link);
    } catch (e) {}
  })();

  // ---- Scratchpad ----
  var STORAGE_SCRATCH = 'homepage.scratch';
  var scratchPanel = document.getElementById('scratchPanel');
  var scratchBtn = document.getElementById('scratchBtn');
  var scratchClose = document.getElementById('scratchClose');
  var scratchText = document.getElementById('scratchText');
  var scratchStatus = document.getElementById('scratchStatus');
  var scratchClear = document.getElementById('scratchClear');
  var scratchTimer = null;

  scratchText.value = localStorage.getItem(STORAGE_SCRATCH) || '';

  function saveScratch() {
    localStorage.setItem(STORAGE_SCRATCH, scratchText.value);
    scratchStatus.textContent = 'Saved';
    clearTimeout(scratchTimer);
    scratchTimer = setTimeout(function () {
      scratchStatus.textContent = 'Saved automatically';
    }, 1500);
  }

  scratchText.addEventListener('input', function () {
    scratchStatus.textContent = 'Saving…';
    clearTimeout(scratchTimer);
    scratchTimer = setTimeout(saveScratch, 400);
  });

  // Checklist syntax: a line starting with "- [ ]" or "- [x]" toggles when
  // clicked near the brackets, since a plain textarea can't host a real
  // checkbox widget. Clicks elsewhere on the line just place the cursor.
  scratchText.addEventListener('click', function () {
    var pos = scratchText.selectionStart;
    var value = scratchText.value;
    var lineStart = value.lastIndexOf('\n', pos - 1) + 1;
    var lineEnd = value.indexOf('\n', lineStart);
    if (lineEnd === -1) lineEnd = value.length;
    var line = value.slice(lineStart, lineEnd);
    var m = line.match(/^- \[([ xX])\]/);
    if (!m || pos - lineStart > 5) return;
    var toggled = (m[1] === ' ' ? '- [x]' : '- [ ]') + line.slice(5);
    scratchText.value = value.slice(0, lineStart) + toggled + value.slice(lineEnd);
    scratchText.selectionStart = scratchText.selectionEnd = pos;
    scratchText.dispatchEvent(new Event('input', { bubbles: true }));
  });

  scratchClear.addEventListener('click', function () {
    if (!scratchText.value || confirm('Clear the scratchpad?')) {
      scratchText.value = '';
      localStorage.setItem(STORAGE_SCRATCH, '');
      scratchStatus.textContent = 'Cleared';
      scratchText.focus();
    }
  });

  function openScratch() {
    settingsPanel.classList.add('hidden');
    scratchPanel.classList.remove('hidden');
    scratchBtn.classList.add('active');
    scratchText.focus();
  }

  function closeScratch() {
    scratchPanel.classList.add('hidden');
    scratchBtn.classList.remove('active');
  }

  function toggleScratch() {
    if (scratchPanel.classList.contains('hidden')) openScratch();
    else closeScratch();
  }

  scratchBtn.addEventListener('click', toggleScratch);
  scratchClose.addEventListener('click', closeScratch);

  // ---- Zen mode ----
  var STORAGE_ZEN = 'homepage.zen';
  var zenBtn = document.getElementById('zenBtn');
  var zenActive = localStorage.getItem(STORAGE_ZEN) === '1';

  function applyZen() {
    document.body.classList.toggle('zen', zenActive);
    zenBtn.classList.toggle('active', zenActive);
    var label = zenActive ? 'Exit zen mode (Z)' : 'Zen mode (Z)';
    zenBtn.title = label;
    zenBtn.setAttribute('aria-label', label);
  }

  function toggleZen() {
    zenActive = !zenActive;
    localStorage.setItem(STORAGE_ZEN, zenActive ? '1' : '0');
    applyZen();
  }

  zenBtn.addEventListener('click', toggleZen);
  applyZen();

  // ---- Export / import ----
  var exportBtn = document.getElementById('exportBtn');
  var importBtn = document.getElementById('importBtn');
  var importFile = document.getElementById('importFile');
  var backupStatus = document.getElementById('backupStatus');
  var backupDefaultText = backupStatus.textContent;

  function flashBackupStatus(msg) {
    backupStatus.textContent = msg;
    setTimeout(function () { backupStatus.textContent = backupDefaultText; }, 3000);
  }

  exportBtn.addEventListener('click', function () {
    var payload = {
      version: 1,
      exportedAt: new Date().toISOString(),
      shortcuts: shortcuts,
      groups: groups,
      theme: localStorage.getItem(STORAGE_THEME) || 'ember',
      colors: colorOverrides,
      engine: engineSelect.value,
      scratch: scratchText.value
    };
    var blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = 'homepage-settings.json';
    a.click();
    URL.revokeObjectURL(url);
    flashBackupStatus('Exported homepage-settings.json');
  });

  importBtn.addEventListener('click', function () { importFile.click(); });

  importFile.addEventListener('change', function () {
    var file = importFile.files && importFile.files[0];
    if (!file) return;
    var reader = new FileReader();
    reader.onload = function () {
      try {
        var data = JSON.parse(reader.result);
        if (!data || typeof data !== 'object') throw new Error('bad file');

        if (Array.isArray(data.groups)) {
          groups = data.groups.filter(function (g) { return typeof g === 'string' && g.trim(); });
          saveGroups(groups);
          activeGroup = 'all';
          localStorage.setItem(STORAGE_ACTIVE_GROUP, activeGroup);
          renderShortcuts();
        }

        if (Array.isArray(data.shortcuts)) {
          var clean = data.shortcuts.filter(function (s) {
            return s && typeof s.name === 'string' && typeof s.url === 'string';
          }).map(function (s) {
            return { name: s.name, url: s.url, group: typeof s.group === 'string' ? s.group : '' };
          });
          if (!confirm('Replace your ' + shortcuts.length + ' shortcuts with ' + clean.length + ' from this file?')) {
            importFile.value = '';
            return;
          }
          shortcuts = clean;
          saveShortcuts(shortcuts);
          renderShortcuts();
        }

        if (data.colors && typeof data.colors === 'object' && !Array.isArray(data.colors)) {
          colorOverrides = data.colors;
          saveColorOverrides();
        }

        if (typeof data.theme === 'string' && THEME_ANIM[data.theme]) {
          applyTheme(data.theme);
        } else {
          applyColorOverrides(document.documentElement.getAttribute('data-theme'));
          updateColorInputs();
          updateFaviconAndMeta();
        }

        if (typeof data.engine === 'string') {
          var found = Array.prototype.some.call(engineSelect.options, function (o) { return o.value === data.engine; });
          if (found) {
            engineSelect.value = data.engine;
            localStorage.setItem(STORAGE_ENGINE, data.engine);
          }
        }

        if (typeof data.scratch === 'string') {
          scratchText.value = data.scratch;
          localStorage.setItem(STORAGE_SCRATCH, data.scratch);
        }

        flashBackupStatus('Settings imported.');
      } catch (err) {
        flashBackupStatus("That file couldn't be read. Pick a homepage settings JSON file.");
      }
      importFile.value = '';
    };
    reader.readAsText(file);
  });

  document.addEventListener('keydown', function (e) {
    var tag = (e.target.tagName || '').toLowerCase();
    var typing = tag === 'input' || tag === 'textarea' || tag === 'select' || e.target.isContentEditable;

    if (e.key === '/' && !typing && !e.metaKey && !e.ctrlKey && !e.altKey) {
      e.preventDefault();
      searchInput.focus();
      searchInput.select();
      return;
    }

    if (e.shiftKey && (e.key === 'S' || e.key === 's') && !typing && !e.metaKey && !e.ctrlKey && !e.altKey) {
      e.preventDefault();
      toggleScratch();
      return;
    }

    if ((e.key === 'z' || e.key === 'Z') && !typing && !e.metaKey && !e.ctrlKey && !e.altKey) {
      e.preventDefault();
      toggleZen();
      return;
    }

    if (e.altKey && !e.metaKey && !e.ctrlKey && /^[1-9]$/.test(e.key)) {
      var idx = parseInt(e.key, 10) - 1;
      var vis = visibleShortcuts();
      if (vis[idx]) {
        e.preventDefault();
        window.open(vis[idx].s.url, '_blank', 'noopener');
      }
      return;
    }

    if (e.key === 'Alt') document.body.classList.add('show-hotkeys');

    if (e.key === 'Escape') {
      if (!modalOverlay.classList.contains('hidden')) {
        closeModal();
      } else if (!scratchPanel.classList.contains('hidden')) {
        closeScratch();
      } else if (!settingsPanel.classList.contains('hidden')) {
        settingsPanel.classList.add('hidden');
      } else if (document.activeElement === searchInput) {
        if (searchInput.value) {
          clearSearch();
        } else {
          resultsEl.classList.add('hidden');
          searchInput.blur();
        }
      } else if (zenActive) {
        toggleZen();
      }
    }
  });

  var commandListEl = document.getElementById('commandList');
  if (commandListEl) {
    commandListEl.innerHTML = COMMANDS.map(function (c) {
      return '<kbd class="k">' + c.prefix + '</kbd> ' + c.label;
    }).join(' &nbsp;·&nbsp; ');
  }

  var savedTheme = localStorage.getItem(STORAGE_THEME) || 'ember';
  applyTheme(savedTheme);
  renderShortcuts();
})();
