// Generated by build-newtab.py from ../index.html — edit that file, not this one.

(function () {
  var STORAGE_SHORTCUTS = 'homepage.shortcuts';
  var STORAGE_THEME = 'homepage.theme';
  var STORAGE_ENGINE = 'homepage.engine';

  var defaultShortcuts = [
    { name: 'GitHub', url: 'https://github.com' },
    { name: 'YouTube', url: 'https://youtube.com' },
    { name: 'Gmail', url: 'https://mail.google.com' },
    { name: 'Reddit', url: 'https://reddit.com' }
  ];

  var editing = false;
  var editingIndex = null;
  var dragIndex = null;

  var grid = document.getElementById('shortcutsGrid');
  var editBtn = document.getElementById('editBtn');
  var settingsBtn = document.getElementById('settingsBtn');
  var settingsPanel = document.getElementById('settingsPanel');
  var panelClose = document.getElementById('panelClose');
  var themeGrid = document.getElementById('themeGrid');
  var modalOverlay = document.getElementById('modalOverlay');
  var modalTitle = document.getElementById('modalTitle');
  var tileNameInput = document.getElementById('tileName');
  var tileUrlInput = document.getElementById('tileUrl');
  var modalSave = document.getElementById('modalSave');
  var modalCancel = document.getElementById('modalCancel');
  var modalDelete = document.getElementById('modalDelete');
  var searchForm = document.getElementById('searchForm');
  var searchInput = document.getElementById('searchInput');
  var engineSelect = document.getElementById('engineSelect');

  function loadShortcuts() {
    try {
      var raw = localStorage.getItem(STORAGE_SHORTCUTS);
      if (raw) return JSON.parse(raw);
    } catch (e) {}
    return defaultShortcuts.slice();
  }

  function saveShortcuts(list) {
    localStorage.setItem(STORAGE_SHORTCUTS, JSON.stringify(list));
  }

  var shortcuts = loadShortcuts();

  // ---- Toast with undo ----
  var toastEl = document.getElementById('toast');
  var toastMsg = document.getElementById('toastMsg');
  var toastAction = document.getElementById('toastAction');
  var toastTimer = null;
  var undoFn = null;

  function showToast(msg, onUndo, actionLabel) {
    toastMsg.textContent = msg;
    undoFn = onUndo || null;
    toastAction.textContent = actionLabel || 'Undo';
    toastAction.style.display = undoFn ? '' : 'none';
    toastEl.classList.add('show');
    clearTimeout(toastTimer);
    toastTimer = setTimeout(hideToast, 6000);
  }

  function hideToast() {
    toastEl.classList.remove('show');
    undoFn = null;
  }

  toastAction.addEventListener('click', function () {
    if (undoFn) undoFn();
    hideToast();
  });

  function normalizeUrl(input) {
    var v = input.trim();
    if (!v) return '';
    if (!/^https?:\/\//i.test(v)) v = 'https://' + v;
    return v;
  }

  function hostnameFor(url) {
    try { return new URL(url).hostname; } catch (e) { return ''; }
  }

  function initialFor(name) {
    return (name.trim().charAt(0) || '?').toUpperCase();
  }

  function removeShortcut(index) {
    var removed = shortcuts[index];
    shortcuts.splice(index, 1);
    saveShortcuts(shortcuts);
    renderShortcuts();
    showToast('Removed ' + removed.name, function () {
      shortcuts.splice(index, 0, removed);
      saveShortcuts(shortcuts);
      renderShortcuts();
    });
  }

  function renderShortcuts() {
    grid.innerHTML = '';
    shortcuts.forEach(function (s, i) {
      var tile = document.createElement(editing ? 'div' : 'a');
      tile.className = 'tile';
      if (!editing) { tile.href = s.url; }
      tile.draggable = editing;
      tile.dataset.index = i;

      var icon = document.createElement('div');
      icon.className = 'tile-icon';
      var host = hostnameFor(s.url);
      if (host) {
        var img = document.createElement('img');
        img.src = 'https://www.google.com/s2/favicons?sz=64&domain=' + host;
        img.alt = '';
        img.onerror = function () {
          icon.innerHTML = '';
          icon.textContent = initialFor(s.name);
        };
        icon.appendChild(img);
      } else {
        icon.textContent = initialFor(s.name);
      }

      var label = document.createElement('div');
      label.className = 'tile-label';
      label.textContent = s.name;

      tile.appendChild(icon);
      tile.appendChild(label);

      if (i < 9) {
        var hk = document.createElement('div');
        hk.className = 'tile-hotkey';
        hk.textContent = i + 1;
        tile.appendChild(hk);
      }

      if (editing) {
        var removeBtn = document.createElement('button');
        removeBtn.className = 'tile-remove';
        removeBtn.textContent = '\u00d7';
        removeBtn.addEventListener('click', function (e) {
          e.stopPropagation();
          removeShortcut(i);
        });
        tile.appendChild(removeBtn);

        tile.addEventListener('click', function (e) {
          e.preventDefault();
          openModal(i);
        });

        tile.addEventListener('dragstart', function () {
          dragIndex = i;
          tile.classList.add('dragging');
        });
        tile.addEventListener('dragend', function () {
          tile.classList.remove('dragging');
        });
        tile.addEventListener('dragover', function (e) {
          e.preventDefault();
        });
        tile.addEventListener('drop', function (e) {
          e.preventDefault();
          if (dragIndex === null || dragIndex === i) return;
          var moved = shortcuts.splice(dragIndex, 1)[0];
          shortcuts.splice(i, 0, moved);
          saveShortcuts(shortcuts);
          dragIndex = null;
          renderShortcuts();
        });
      }

      grid.appendChild(tile);
    });

    var addTile = document.createElement('div');
    addTile.className = 'tile add-tile';
    var addIcon = document.createElement('div');
    addIcon.className = 'tile-icon';
    addIcon.textContent = '+';
    var addLabel = document.createElement('div');
    addLabel.className = 'tile-label';
    addLabel.textContent = 'Add';
    addTile.appendChild(addIcon);
    addTile.appendChild(addLabel);
    addTile.addEventListener('click', function () { openModal(null); });
    grid.appendChild(addTile);
  }

  function openModal(index) {
    editingIndex = index;
    if (index === null) {
      modalTitle.textContent = 'Add shortcut';
      tileNameInput.value = '';
      tileUrlInput.value = '';
      modalDelete.classList.add('hidden');
    } else {
      modalTitle.textContent = 'Edit shortcut';
      tileNameInput.value = shortcuts[index].name;
      tileUrlInput.value = shortcuts[index].url;
      modalDelete.classList.remove('hidden');
    }
    modalOverlay.classList.remove('hidden');
    tileNameInput.focus();
  }

  function closeModal() {
    modalOverlay.classList.add('hidden');
    editingIndex = null;
  }

  modalCancel.addEventListener('click', closeModal);
  modalOverlay.addEventListener('click', function (e) {
    if (e.target === modalOverlay) closeModal();
  });

  modalSave.addEventListener('click', function () {
    var name = tileNameInput.value.trim();
    var url = normalizeUrl(tileUrlInput.value);
    if (!name || !url) return;

    var host = hostnameFor(url).replace(/^www\./, '');
    var dupe = shortcuts.findIndex(function (s, i) {
      return i !== editingIndex && hostnameFor(s.url).replace(/^www\./, '') === host;
    });
    if (host && dupe > -1) {
      if (!confirm(shortcuts[dupe].name + ' already points to ' + host + '. Add this anyway?')) return;
    }

    if (editingIndex === null) {
      shortcuts.push({ name: name, url: url });
    } else {
      shortcuts[editingIndex] = { name: name, url: url };
    }
    saveShortcuts(shortcuts);
    closeModal();
    renderShortcuts();
  });

  modalDelete.addEventListener('click', function () {
    if (editingIndex === null) return;
    var idx = editingIndex;
    closeModal();
    removeShortcut(idx);
  });

  editBtn.addEventListener('click', function () {
    editing = !editing;
    document.body.classList.toggle('editing', editing);
    editBtn.classList.toggle('active', editing);
    renderShortcuts();
  });

  settingsBtn.addEventListener('click', function () {
    scratchPanel.classList.add('hidden');
    scratchBtn.classList.remove('active');
    settingsPanel.classList.remove('hidden');
  });
  panelClose.addEventListener('click', function () {
    settingsPanel.classList.add('hidden');
  });

  function applyTheme(theme) {
    document.documentElement.setAttribute('data-theme', theme);
    localStorage.setItem(STORAGE_THEME, theme);
    Array.prototype.forEach.call(themeGrid.children, function (btn) {
      btn.classList.toggle('active', btn.dataset.swatch === theme);
    });
    var cs = getComputedStyle(document.documentElement);
    var bg = cs.getPropertyValue('--bg').trim();
    var accent = cs.getPropertyValue('--accent').trim();
    var meta = document.getElementById('themeColorMeta');
    if (meta && bg) meta.setAttribute('content', bg);
    var fav = document.getElementById('favicon');
    if (fav && bg && accent) {
      fav.href = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='"
        + encodeURIComponent(bg)
        + "'/%3E%3Cpath d='M16 34 32 20l16 14v14a2 2 0 0 1-2 2H34V40h-4v10H18a2 2 0 0 1-2-2z' fill='"
        + encodeURIComponent(accent)
        + "'/%3E%3C/svg%3E";
    }
    renderParticles(theme);
  }

  themeGrid.addEventListener('click', function (e) {
    var btn = e.target.closest('.swatch');
    if (!btn) return;
    applyTheme(btn.dataset.swatch);
  });

  var particlesEl = document.getElementById('particles');
  var particleTimer = null;

  function rand(min, max) { return min + Math.random() * (max - min); }

  var THEME_ANIM = {
    ember:    { type: 'rise',    color: 'var(--accent-2)', size: [2, 4], duration: [6, 12],  interval: 850, seed: 6 },
    forest:   { type: 'firefly', color: 'var(--accent-2)', count: 12,    size: [2, 4] },
    noir:     { type: 'twinkle', count: 45,                size: [1, 2] },
    aurora:   { type: 'aurora',  stars: 20 },
    daybreak: { type: 'firefly', color: 'var(--accent-2)', count: 14,    size: [1.5, 3] },
    frost:    { type: 'fall',    color: '#ffffff',         size: [2, 4], duration: [8, 15],  interval: 750, seed: 6 },
    sunset:   { type: 'clouds' },
    bloom:    { type: 'fall',    color: 'var(--accent-2)', size: [6, 10], duration: [9, 16],  interval: 1000, seed: 5, petal: true }
  };

  function clearParticles() {
    particlesEl.innerHTML = '';
    if (particleTimer) { clearInterval(particleTimer); particleTimer = null; }
  }

  function spawnRiseOrFall(cfg, kind) {
    function spawn() {
      var p = document.createElement('div');
      p.className = kind === 'rise' ? 'ember-particle' : ('fall-particle' + (cfg.petal ? ' petal' : ''));
      var size = rand(cfg.size[0], cfg.size[1]);
      var duration = rand(cfg.duration[0], cfg.duration[1]);
      var drift = rand(-30, 30) + 'px';
      p.style.left = rand(0, 100) + 'vw';
      p.style.width = size + 'px';
      p.style.height = size + 'px';
      p.style.setProperty('--drift', drift);
      p.style.setProperty('--particle-color', cfg.color);
      if (cfg.petal) p.style.setProperty('--spin', rand(180, 540) + 'deg');
      p.style.background = cfg.color;
      p.style.boxShadow = cfg.petal ? 'none' : ('0 0 6px 1px ' + cfg.color);
      p.style.animationDuration = duration + 's';
      particlesEl.appendChild(p);
      setTimeout(function () { p.remove(); }, duration * 1000);
    }
    for (var i = 0; i < cfg.seed; i++) setTimeout(spawn, i * (cfg.interval * 0.7));
    particleTimer = setInterval(spawn, cfg.interval);
  }

  function spawnStars(count) {
    for (var i = 0; i < count; i++) {
      var s = document.createElement('div');
      s.className = 'star';
      var size = rand(1, 2.4);
      s.style.left = rand(0, 100) + 'vw';
      s.style.top = rand(0, 65) + 'vh';
      s.style.width = size + 'px';
      s.style.height = size + 'px';
      s.style.animationDuration = rand(2, 5) + 's';
      s.style.animationDelay = rand(0, 4) + 's';
      particlesEl.appendChild(s);
    }
  }

  function spawnFireflies(cfg) {
    for (var i = 0; i < cfg.count; i++) {
      var f = document.createElement('div');
      f.className = 'firefly';
      var size = rand(cfg.size[0], cfg.size[1]);
      f.style.left = rand(0, 100) + 'vw';
      f.style.top = rand(10, 85) + 'vh';
      f.style.width = size + 'px';
      f.style.height = size + 'px';
      f.style.setProperty('--particle-color', cfg.color);
      f.style.background = cfg.color;
      f.style.setProperty('--fx1', rand(-30, 30) + 'px');
      f.style.setProperty('--fy1', rand(-30, 30) + 'px');
      f.style.setProperty('--fx2', rand(-30, 30) + 'px');
      f.style.setProperty('--fy2', rand(-30, 30) + 'px');
      f.style.setProperty('--fx3', rand(-30, 30) + 'px');
      f.style.setProperty('--fy3', rand(-30, 30) + 'px');
      f.style.animationDuration = rand(7, 13) + 's, ' + rand(2, 4) + 's';
      f.style.animationDelay = rand(0, 4) + 's';
      particlesEl.appendChild(f);
    }
  }

  function buildClouds() {
    var count = 4;
    for (var i = 0; i < count; i++) {
      var c = document.createElement('div');
      c.className = 'cloud';
      var size = rand(140, 300);
      c.style.top = rand(4, 34) + 'vh';
      c.style.width = size + 'px';
      c.style.height = size * 0.5 + 'px';
      c.style.animationDuration = rand(45, 80) + 's';
      c.style.animationDelay = '-' + rand(0, 60) + 's';
      particlesEl.appendChild(c);
    }
  }

  function buildAurora() {
    var colors = ['var(--accent)', 'var(--accent-2)', 'var(--accent)'];
    for (var i = 0; i < 3; i++) {
      var b = document.createElement('div');
      b.className = 'aurora-blob';
      var size = rand(260, 420);
      b.style.width = size + 'px';
      b.style.height = size + 'px';
      b.style.left = rand(-10, 70) + 'vw';
      b.style.top = rand(-10, 20) + 'vh';
      b.style.background = colors[i];
      b.style.opacity = 0.35;
      b.style.animationDuration = rand(14, 22) + 's';
      b.style.animationDelay = '-' + rand(0, 15) + 's';
      particlesEl.appendChild(b);
    }
  }

  function renderParticles(theme) {
    clearParticles();
    var cfg = THEME_ANIM[theme];
    if (!cfg) return;
    if (cfg.type === 'rise' || cfg.type === 'fall') spawnRiseOrFall(cfg, cfg.type);
    else if (cfg.type === 'twinkle') spawnStars(cfg.count);
    else if (cfg.type === 'firefly') spawnFireflies(cfg);
    else if (cfg.type === 'clouds') buildClouds();
    else if (cfg.type === 'aurora') { buildAurora(); spawnStars(cfg.stars); }
  }

  function greetingFor(hour) {
    if (hour >= 5 && hour < 12) return 'Good morning';
    if (hour >= 12 && hour < 17) return 'Good afternoon';
    if (hour >= 17 && hour < 21) return 'Good evening';
    return 'Good night';
  }

  function tick() {
    var now = new Date();
    var h = now.getHours();
    var m = now.getMinutes();
    var clockStr = (h % 12 === 0 ? 12 : h % 12) + ':' + (m < 10 ? '0' : '') + m + (h < 12 ? ' AM' : ' PM');
    document.getElementById('clock').textContent = clockStr;
    document.getElementById('greeting').textContent = greetingFor(h);
    var days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
    var months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
    document.getElementById('date').textContent = days[now.getDay()] + ', ' + months[now.getMonth()] + ' ' + now.getDate();
  }
  tick();
  setInterval(tick, 1000 * 15);

  var savedEngine = localStorage.getItem(STORAGE_ENGINE);
  if (savedEngine) engineSelect.value = savedEngine;
  engineSelect.addEventListener('change', function () {
    localStorage.setItem(STORAGE_ENGINE, engineSelect.value);
  });

  // ---- Launcher ----
  var resultsEl = document.getElementById('results');
  var matches = [];
  var selectedIdx = 0;

  var COMMANDS = [
    { prefix: 'g',  label: 'Google',        url: 'https://www.google.com/search?q=' },
    { prefix: 'd',  label: 'DuckDuckGo',    url: 'https://duckduckgo.com/?q=' },
    { prefix: 'y',  label: 'YouTube',       url: 'https://www.youtube.com/results?search_query=' },
    { prefix: 'gh', label: 'GitHub',        url: 'https://github.com/search?q=' },
    { prefix: 'w',  label: 'Wikipedia',     url: 'https://en.wikipedia.org/w/index.php?search=' },
    { prefix: 'r',  label: 'Reddit',        url: 'https://www.reddit.com/search/?q=' },
    { prefix: 'a',  label: 'Amazon',        url: 'https://www.amazon.com/s?k=' },
    { prefix: 'm',  label: 'Maps',          url: 'https://www.google.com/maps/search/' },
    { prefix: 'i',  label: 'Images',        url: 'https://www.google.com/search?tbm=isch&q=' },
    { prefix: 'np', label: 'npm',           url: 'https://www.npmjs.com/search?q=' },
    { prefix: 'mdn',label: 'MDN',           url: 'https://developer.mozilla.org/en-US/search?q=' },
    { prefix: 'so', label: 'Stack Overflow',url: 'https://stackoverflow.com/search?q=' }
  ];

  function parseCommand(q) {
    var m = q.match(/^(\S+)\s+(.*)$/);
    if (!m) return null;
    var cmd = COMMANDS.find(function (c) { return c.prefix === m[1].toLowerCase(); });
    if (!cmd || !m[2].trim()) return null;
    return { cmd: cmd, term: m[2].trim() };
  }

  function partialCommands(q) {
    var v = q.trim().toLowerCase();
    if (!v || /\s/.test(v)) return [];
    return COMMANDS.filter(function (c) { return c.prefix.indexOf(v) === 0; });
  }

  function scoreMatch(shortcut, q) {
    var name = shortcut.name.toLowerCase();
    var host = hostnameFor(shortcut.url).toLowerCase().replace(/^www\./, '');
    if (name === q || host === q) return 0;
    if (name.indexOf(q) === 0) return 1;
    if (host.indexOf(q) === 0) return 2;
    if (name.indexOf(q) > -1) return 3;
    if (host.indexOf(q) > -1) return 4;
    return -1;
  }

  function computeMatches(q) {
    q = q.trim().toLowerCase();
    if (!q) return [];
    return shortcuts
      .map(function (s, i) { return { s: s, i: i, score: scoreMatch(s, q) }; })
      .filter(function (m) { return m.score > -1; })
      .sort(function (a, b) { return a.score - b.score; })
      .slice(0, 6)
      .map(function (m) { return m.s; });
  }

  function looksLikeUrl(q) {
    var v = q.trim();
    if (/\s/.test(v)) return false;
    return /^https?:\/\//i.test(v) || /^[\w-]+(\.[\w-]+)+(\/.*)?$/.test(v);
  }

  function renderResults() {
    var q = searchInput.value;
    resultsEl.innerHTML = '';

    if (!q.trim()) {
      resultsEl.classList.add('hidden');
      matches = [];
      return;
    }

    var rows = [];
    var parsed = parseCommand(q);

    if (parsed) {
      rows.push({
        kind: 'command',
        label: parsed.term,
        sub: 'on ' + parsed.cmd.label,
        prefix: parsed.cmd.prefix,
        url: parsed.cmd.url + encodeURIComponent(parsed.term)
      });
    }

    matches = computeMatches(q);
    matches.forEach(function (s) {
      rows.push({ kind: 'shortcut', label: s.name, url: s.url });
    });

    partialCommands(q).forEach(function (c) {
      rows.push({ kind: 'hint', label: 'Search ' + c.label, prefix: c.prefix, hint: true });
    });

    if (!parsed) {
      if (looksLikeUrl(q)) {
        rows.push({ kind: 'open', label: q.trim(), url: normalizeUrl(q) });
      }
      rows.push({
        kind: 'search',
        label: q.trim(),
        url: engineSelect.value + encodeURIComponent(q.trim())
      });
    }

    if (selectedIdx >= rows.length) selectedIdx = 0;

    rows.forEach(function (row, i) {
      var el = document.createElement('div');
      el.className = 'result' + (i === selectedIdx ? ' selected' : '');

      if (row.kind === 'shortcut') {
        var host = hostnameFor(row.url);
        var img = document.createElement('img');
        img.src = 'https://www.google.com/s2/favicons?sz=64&domain=' + host;
        img.alt = '';
        img.onerror = function () {
          var fb = document.createElement('div');
          fb.className = 'result-fallback';
          fb.textContent = initialFor(row.label);
          img.replaceWith(fb);
        };
        el.appendChild(img);
      } else {
        var glyph = document.createElement('div');
        glyph.className = 'result-fallback';
        glyph.textContent = row.kind === 'open' ? '\u2197' : '\u2315';
        el.appendChild(glyph);
      }

      var text = document.createElement('div');
      text.className = 'result-text';
      text.textContent = row.label;
      if (row.sub) {
        var sub = document.createElement('span');
        sub.className = 'result-host';
        sub.textContent = row.sub;
        text.appendChild(sub);
      }
      el.appendChild(text);

      if (row.prefix) {
        var pf = document.createElement('div');
        pf.className = 'result-prefix';
        pf.textContent = row.prefix + ' \u2026';
        el.appendChild(pf);
      }

      var kind = document.createElement('div');
      kind.className = 'result-kind';
      kind.textContent = row.kind === 'shortcut' ? 'Shortcut'
        : row.kind === 'open' ? 'Open'
        : row.kind === 'hint' ? 'Command'
        : row.kind === 'command' ? 'Go'
        : 'Search';
      el.appendChild(kind);

      el.addEventListener('mouseenter', function () {
        selectedIdx = i;
        Array.prototype.forEach.call(resultsEl.children, function (c, ci) {
          c.classList.toggle('selected', ci === i);
        });
      });

      el.addEventListener('click', function () {
        if (row.hint) {
          searchInput.value = row.prefix + ' ';
          selectedIdx = 0;
          searchInput.focus();
          renderResults();
        } else {
          go(row.url);
        }
      });

      resultsEl.appendChild(el);
    });

    resultsEl.classList.remove('hidden');
  }

  function go(url) {
    window.location.href = url;
  }

  function activateSelection() {
    var rows = resultsEl.children;
    if (!rows.length) {
      var q = searchInput.value.trim();
      if (q) go(engineSelect.value + encodeURIComponent(q));
      return;
    }
    rows[selectedIdx] && rows[selectedIdx].click();
  }

  function moveSelection(delta) {
    var count = resultsEl.children.length;
    if (!count) return;
    selectedIdx = (selectedIdx + delta + count) % count;
    Array.prototype.forEach.call(resultsEl.children, function (c, ci) {
      c.classList.toggle('selected', ci === selectedIdx);
    });
    var sel = resultsEl.children[selectedIdx];
    if (sel && sel.scrollIntoView) sel.scrollIntoView({ block: 'nearest' });
  }

  searchInput.addEventListener('input', function () {
    selectedIdx = 0;
    renderResults();
  });

  searchInput.addEventListener('keydown', function (e) {
    if (e.key === 'ArrowDown') { e.preventDefault(); moveSelection(1); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); moveSelection(-1); }
  });

  searchInput.addEventListener('focus', renderResults);

  searchInput.addEventListener('blur', function () {
    setTimeout(function () { resultsEl.classList.add('hidden'); }, 150);
  });

  engineSelect.addEventListener('change', renderResults);

  searchForm.addEventListener('submit', function (e) {
    e.preventDefault();
    activateSelection();
  });

  document.addEventListener('keyup', function (e) {
    if (e.key === 'Alt') document.body.classList.remove('show-hotkeys');
  });
  window.addEventListener('blur', function () {
    document.body.classList.remove('show-hotkeys');
  });

  // ---- Pause background animation when the tab isn't visible ----
  document.addEventListener('visibilitychange', function () {
    if (document.hidden) {
      if (particleTimer) { clearInterval(particleTimer); particleTimer = null; }
      particlesEl.style.animationPlayState = 'paused';
      particlesEl.querySelectorAll('*').forEach(function (el) {
        el.style.animationPlayState = 'paused';
      });
    } else {
      renderParticles(document.documentElement.getAttribute('data-theme'));
    }
  });

  // ---- Installable app manifest ----
  (function () {
    var icon = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='%230a0606'/%3E%3Cpath d='M16 34 32 20l16 14v14a2 2 0 0 1-2 2H34V40h-4v10H18a2 2 0 0 1-2-2z' fill='%23e0362b'/%3E%3C/svg%3E";
    var manifest = {
      name: 'Home',
      short_name: 'Home',
      description: 'A custom browser home page.',
      start_url: '.',
      display: 'standalone',
      background_color: '#0a0606',
      theme_color: '#0a0606',
      icons: [
        { src: icon, sizes: 'any', type: 'image/svg+xml', purpose: 'any' }
      ]
    };
    try {
      var blob = new Blob([JSON.stringify(manifest)], { type: 'application/manifest+json' });
      var link = document.createElement('link');
      link.rel = 'manifest';
      link.href = URL.createObjectURL(blob);
      document.head.appendChild(link);
    } catch (e) {}
  })();

  // ---- Scratchpad ----
  var STORAGE_SCRATCH = 'homepage.scratch';
  var scratchPanel = document.getElementById('scratchPanel');
  var scratchBtn = document.getElementById('scratchBtn');
  var scratchClose = document.getElementById('scratchClose');
  var scratchText = document.getElementById('scratchText');
  var scratchStatus = document.getElementById('scratchStatus');
  var scratchClear = document.getElementById('scratchClear');
  var scratchTimer = null;

  scratchText.value = localStorage.getItem(STORAGE_SCRATCH) || '';

  function saveScratch() {
    localStorage.setItem(STORAGE_SCRATCH, scratchText.value);
    scratchStatus.textContent = 'Saved';
    clearTimeout(scratchTimer);
    scratchTimer = setTimeout(function () {
      scratchStatus.textContent = 'Saved automatically';
    }, 1500);
  }

  scratchText.addEventListener('input', function () {
    scratchStatus.textContent = 'Saving…';
    clearTimeout(scratchTimer);
    scratchTimer = setTimeout(saveScratch, 400);
  });

  scratchClear.addEventListener('click', function () {
    if (!scratchText.value || confirm('Clear the scratchpad?')) {
      scratchText.value = '';
      localStorage.setItem(STORAGE_SCRATCH, '');
      scratchStatus.textContent = 'Cleared';
      scratchText.focus();
    }
  });

  function openScratch() {
    settingsPanel.classList.add('hidden');
    scratchPanel.classList.remove('hidden');
    scratchBtn.classList.add('active');
    scratchText.focus();
  }

  function closeScratch() {
    scratchPanel.classList.add('hidden');
    scratchBtn.classList.remove('active');
  }

  function toggleScratch() {
    if (scratchPanel.classList.contains('hidden')) openScratch();
    else closeScratch();
  }

  scratchBtn.addEventListener('click', toggleScratch);
  scratchClose.addEventListener('click', closeScratch);

  // ---- Export / import ----
  var exportBtn = document.getElementById('exportBtn');
  var importBtn = document.getElementById('importBtn');
  var importFile = document.getElementById('importFile');
  var backupStatus = document.getElementById('backupStatus');
  var backupDefaultText = backupStatus.textContent;

  function flashBackupStatus(msg) {
    backupStatus.textContent = msg;
    setTimeout(function () { backupStatus.textContent = backupDefaultText; }, 3000);
  }

  exportBtn.addEventListener('click', function () {
    var payload = {
      version: 1,
      exportedAt: new Date().toISOString(),
      shortcuts: shortcuts,
      theme: localStorage.getItem(STORAGE_THEME) || 'ember',
      engine: engineSelect.value,
      scratch: scratchText.value
    };
    var blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = 'homepage-settings.json';
    a.click();
    URL.revokeObjectURL(url);
    flashBackupStatus('Exported homepage-settings.json');
  });

  importBtn.addEventListener('click', function () { importFile.click(); });

  importFile.addEventListener('change', function () {
    var file = importFile.files && importFile.files[0];
    if (!file) return;
    var reader = new FileReader();
    reader.onload = function () {
      try {
        var data = JSON.parse(reader.result);
        if (!data || typeof data !== 'object') throw new Error('bad file');

        if (Array.isArray(data.shortcuts)) {
          var clean = data.shortcuts.filter(function (s) {
            return s && typeof s.name === 'string' && typeof s.url === 'string';
          }).map(function (s) {
            return { name: s.name, url: s.url };
          });
          if (!confirm('Replace your ' + shortcuts.length + ' shortcuts with ' + clean.length + ' from this file?')) {
            importFile.value = '';
            return;
          }
          shortcuts = clean;
          saveShortcuts(shortcuts);
          renderShortcuts();
        }

        if (typeof data.theme === 'string' && THEME_ANIM[data.theme]) applyTheme(data.theme);

        if (typeof data.engine === 'string') {
          var found = Array.prototype.some.call(engineSelect.options, function (o) { return o.value === data.engine; });
          if (found) {
            engineSelect.value = data.engine;
            localStorage.setItem(STORAGE_ENGINE, data.engine);
          }
        }

        if (typeof data.scratch === 'string') {
          scratchText.value = data.scratch;
          localStorage.setItem(STORAGE_SCRATCH, data.scratch);
        }

        flashBackupStatus('Settings imported.');
      } catch (err) {
        flashBackupStatus("That file couldn't be read. Pick a homepage settings JSON file.");
      }
      importFile.value = '';
    };
    reader.readAsText(file);
  });

  document.addEventListener('keydown', function (e) {
    var tag = (e.target.tagName || '').toLowerCase();
    var typing = tag === 'input' || tag === 'textarea' || tag === 'select' || e.target.isContentEditable;

    if (e.key === '/' && !typing && !e.metaKey && !e.ctrlKey && !e.altKey) {
      e.preventDefault();
      searchInput.focus();
      searchInput.select();
      return;
    }

    if (e.shiftKey && (e.key === 'S' || e.key === 's') && !typing && !e.metaKey && !e.ctrlKey && !e.altKey) {
      e.preventDefault();
      toggleScratch();
      return;
    }

    if (e.altKey && !e.metaKey && !e.ctrlKey && /^[1-9]$/.test(e.key)) {
      var idx = parseInt(e.key, 10) - 1;
      if (shortcuts[idx]) {
        e.preventDefault();
        window.location.href = shortcuts[idx].url;
      }
      return;
    }

    if (e.key === 'Alt') document.body.classList.add('show-hotkeys');

    if (e.key === 'Escape') {
      if (!modalOverlay.classList.contains('hidden')) {
        closeModal();
      } else if (!scratchPanel.classList.contains('hidden')) {
        closeScratch();
      } else if (!settingsPanel.classList.contains('hidden')) {
        settingsPanel.classList.add('hidden');
      } else if (document.activeElement === searchInput) {
        resultsEl.classList.add('hidden');
        searchInput.blur();
      }
    }
  });

  var commandListEl = document.getElementById('commandList');
  if (commandListEl) {
    commandListEl.innerHTML = COMMANDS.map(function (c) {
      return '<kbd class="k">' + c.prefix + '</kbd> ' + c.label;
    }).join(' &nbsp;·&nbsp; ');
  }

  var savedTheme = localStorage.getItem(STORAGE_THEME) || 'ember';
  applyTheme(savedTheme);
  renderShortcuts();
})();
